import './global.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { HomeProvider } from "./home_provider";
import { CrashPage } from "./crash";
import { cookies } from 'next/headers'
import styles from './global.module.scss';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teste",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const cookieStore = cookies()
  const theme = cookieStore.get('theme')

  return (
    <html lang="en" data-theme={theme?.value}>
      <body className={inter.className}>
        <CrashPage />
        <button className={styles.button}>
          Clique em mim
        </button>
        <HomeProvider>{children}</HomeProvider>
      </body>
    </html>
  );
}
